# Generated by Django 3.1 on 2020-09-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseoutline_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='course_description',
            field=models.TextField(default=1),
        ),
    ]
