# Generated by Django 3.1 on 2020-09-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200915_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='course_profile_pics'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
